/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import org.example.controller.JFrameController;

/**
 *
 * @author ericp
 */
public class JPanelPedido extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPedido
     */
    public JPanelPedido() {
        initComponents();
        this.setSize(800,700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCrearPedido = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        btnCompletar = new javax.swing.JButton();
        btnTransitar = new javax.swing.JButton();
        btnDespachar = new javax.swing.JButton();
        btnDespacho = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnDestino = new javax.swing.JButton();
        btnEntregar = new javax.swing.JButton();

        setBackground(new java.awt.Color(34, 131, 210));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 245, 255));
        jLabel1.setText("Gestion de Pedidos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 245, 255));
        jLabel2.setText("Por favor seleccione la opcion que desee");

        btnCrearPedido.setBackground(new java.awt.Color(0, 0, 102));
        btnCrearPedido.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCrearPedido.setForeground(new java.awt.Color(0, 195, 225));
        btnCrearPedido.setText("CREAR PEDIDO");
        btnCrearPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPedidoActionPerformed(evt);
            }
        });

        btnProcesar.setBackground(new java.awt.Color(0, 0, 102));
        btnProcesar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnProcesar.setForeground(new java.awt.Color(0, 195, 225));
        btnProcesar.setText("PROCESAR PEDIDO");
        btnProcesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        btnCompletar.setBackground(new java.awt.Color(0, 0, 102));
        btnCompletar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnCompletar.setForeground(new java.awt.Color(0, 195, 225));
        btnCompletar.setText("COMPLETAR PEDIDO");
        btnCompletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCompletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletarActionPerformed(evt);
            }
        });

        btnTransitar.setBackground(new java.awt.Color(0, 0, 102));
        btnTransitar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnTransitar.setForeground(new java.awt.Color(0, 195, 225));
        btnTransitar.setText("TRANSITAR PEDIDO");
        btnTransitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransitarActionPerformed(evt);
            }
        });

        btnDespachar.setBackground(new java.awt.Color(0, 0, 102));
        btnDespachar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDespachar.setForeground(new java.awt.Color(0, 195, 225));
        btnDespachar.setText("DESPACHAR PEDIDO");
        btnDespachar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDespachar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespacharActionPerformed(evt);
            }
        });

        btnDespacho.setBackground(new java.awt.Color(0, 0, 102));
        btnDespacho.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDespacho.setForeground(new java.awt.Color(0, 195, 225));
        btnDespacho.setText("ENVIAR A DESPACHO");
        btnDespacho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespachoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(217, 74, 51));
        btnSalir.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnDestino.setBackground(new java.awt.Color(0, 0, 102));
        btnDestino.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnDestino.setForeground(new java.awt.Color(0, 195, 225));
        btnDestino.setText("ENVIAR A DÉPOSITO DESTINO");
        btnDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinoActionPerformed(evt);
            }
        });

        btnEntregar.setBackground(new java.awt.Color(0, 0, 102));
        btnEntregar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnEntregar.setForeground(new java.awt.Color(0, 195, 225));
        btnEntregar.setText("ENTREGAR PEDIDO");
        btnEntregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                            .addComponent(btnCrearPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(btnCompletar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDespachar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTransitar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                        .addComponent(btnEntregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompletar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDespachar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransitar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPedidoActionPerformed
        JFrameController.cambiarPanel(this, new JPanelCrearPedidoPrimer(),this);
    }//GEN-LAST:event_btnCrearPedidoActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        JFrameController.cambiarPanel(this, new JPanelConsultaCliente(),this);
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnCompletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletarActionPerformed
        JFrameController.cambiarPanel(this, new JPanelPrincipal(), this);
    }//GEN-LAST:event_btnCompletarActionPerformed

    private void btnTransitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransitarActionPerformed

    private void btnDespacharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespacharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDespacharActionPerformed

    private void btnDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDespachoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        JFrameController.cambiarPanel(this, new JPanelPrincipal(), this);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDestinoActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompletar;
    private javax.swing.JButton btnCrearPedido;
    private javax.swing.JButton btnDespachar;
    private javax.swing.JButton btnDespacho;
    private javax.swing.JButton btnDestino;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTransitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
