/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.example.view;

import java.awt.Color;
import org.example.controller.JFrameController;

/**
 *
 * @author ericp
 */
public class JPanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form JPanelPrincipal
     */
    public JPanelPrincipal() {
        initComponents();
        this.setSize(785, 700);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnProduc = new javax.swing.JButton();
        btnTransportista = new javax.swing.JButton();
        btnProveedor = new javax.swing.JButton();
        btnDepositos = new javax.swing.JButton();
        btnEmpleado = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a LDE");

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setBackground(new java.awt.Color(0, 51, 153));
        btnCliente.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(224, 255, 255));
        btnCliente.setText("Clientes");
        btnCliente.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 50));

        btnProduc.setBackground(new java.awt.Color(0, 51, 153));
        btnProduc.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnProduc.setForeground(new java.awt.Color(224, 255, 255));
        btnProduc.setText("Productos");
        btnProduc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnProduc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProducActionPerformed(evt);
            }
        });
        jPanel2.add(btnProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 280, 50));

        btnTransportista.setBackground(new java.awt.Color(0, 51, 153));
        btnTransportista.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnTransportista.setForeground(new java.awt.Color(224, 255, 255));
        btnTransportista.setText("Transportistas");
        btnTransportista.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnTransportista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransportista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnTransportista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransportistaActionPerformed(evt);
            }
        });
        jPanel2.add(btnTransportista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 280, 50));

        btnProveedor.setBackground(new java.awt.Color(0, 51, 153));
        btnProveedor.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnProveedor.setForeground(new java.awt.Color(224, 255, 255));
        btnProveedor.setText("Proveedores");
        btnProveedor.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 280, 50));

        btnDepositos.setBackground(new java.awt.Color(0, 51, 153));
        btnDepositos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnDepositos.setForeground(new java.awt.Color(224, 255, 255));
        btnDepositos.setText("Dépositos");
        btnDepositos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        btnDepositos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepositos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositosActionPerformed(evt);
            }
        });
        jPanel2.add(btnDepositos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 280, 50));

        btnEmpleado.setBackground(new java.awt.Color(0, 51, 153));
        btnEmpleado.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnEmpleado.setForeground(new java.awt.Color(224, 255, 255));
        btnEmpleado.setText("Empleados");
        btnEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseReleased(evt);
            }
        });
        btnEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 50));

        btnPedido.setBackground(new java.awt.Color(0, 51, 153));
        btnPedido.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnPedido.setForeground(new java.awt.Color(224, 255, 255));
        btnPedido.setText("Pedidos");
        btnPedido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 50));

        btnInformes.setBackground(new java.awt.Color(0, 51, 153));
        btnInformes.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnInformes.setForeground(new java.awt.Color(224, 255, 255));
        btnInformes.setText("Informes");
        btnInformes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        btnInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
        });
        jPanel2.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositosActionPerformed
        JFrameController.cambiarPanel(this, new JPanelDeposito(), this);
    }//GEN-LAST:event_btnDepositosActionPerformed

    private void btnEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseEntered

    }//GEN-LAST:event_btnEmpleadoMouseEntered

    private void btnEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseExited

    }//GEN-LAST:event_btnEmpleadoMouseExited

    private void btnEmpleadoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseReleased

    }//GEN-LAST:event_btnEmpleadoMouseReleased

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        JFrameController.cambiarPanel(this, new JPanelCliente(), this);
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        JFrameController.cambiarPanel(this, new JPanelProveedor(), this);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProducActionPerformed
       JFrameController.cambiarPanel(this, new JPanelProducto(), this);
    }//GEN-LAST:event_btnProducActionPerformed

    private void btnTransportistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransportistaActionPerformed
       JFrameController.cambiarPanel(this, new JPanelTransportista(), this);
    }//GEN-LAST:event_btnTransportistaActionPerformed

    private void btnEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadoActionPerformed
        JFrameController.cambiarPanel(this, new JPanelEmpleado(), this);
    }//GEN-LAST:event_btnEmpleadoActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        JFrameController.cambiarPanel(this, new JPanelPedido(), this);
    }//GEN-LAST:event_btnPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnDepositos;
    private javax.swing.JButton btnEmpleado;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnProduc;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton btnTransportista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
